Upload configures for external XenServer CI.

diff --git a/jenkins/jobs/jobs.yaml b/jenkins/jobs/jobs.yaml
--- a/jenkins/jobs/jobs.yaml
+++ b/jenkins/jobs/jobs.yaml
@@ -1,5 +1,5 @@
 - job-template:
-    name: 'dsvm-tempest-xen'
+    name: 'dsvm-tempest-nova-network'
     node: '{node}'
 
     wrappers:
@@ -10,48 +10,231 @@
 
     builders:
       - net-info
-      - devstack-checkout
       - shell: |
           #!/bin/bash -xe
+          set +xe
+          sudo  sed -i '1i\192.168.33.2 localhost.localdomain' /etc/hosts
+          sudo  sed -i '1i\10.71.212.50 openstack-jenkins' /etc/hosts
+          pushd /opt/git/openstack-infra/devstack-gate
+          sudo /usr/bin/git remote update
+          sudo /usr/bin/git checkout origin/master
+          popd
 
-          function pre_test_hook {{
-              echo "Install thirdparty libraries"
-
-              # Install libvirt here to ensure it is
-              # not replaced devstack
-              sudo dpkg -i /opt/nodepool-scripts/*.deb
-              sudo apt-get install -y -f --fix-missing
-          }}
-
-          function cleanup_host_hook {{
-              echo "Copying custom logs"
-
-              # Xen logs
-              if [ -d /var/log/xen ]; then
-                  sudo cp -r /var/log/xen $BASE/logs/
-              fi
-          }}
-
-          export -f pre_test_hook
-          export -f cleanup_host_hook
-
-          if [ -z $ZUUL_PROJECT ]; then
-              export ZUUL_PROJECT=openstack-dev/sandbox
+          if [ 1 -eq 1 ]
+          then
+          # start of create VG on memory
+          VG=stack-volumes-lvmdriver-1
+          LVMNT="/memmnt"
+          sudo mkdir -p $LVMNT
+          sudo mount -t tmpfs -o size=6G tmpfs $LVMNT
+          sudo truncate -s 24G $LVMNT/$VG
+          sudo chmod 777 $LVMNT/$VG
+          VG_DEV=$(sudo losetup -f --show $LVMNT/$VG)
+          sudo vgcreate $VG $VG_DEV
+          # end of create VG on memory 
           fi
-          if [ -z $ZUUL_BRANCH ]; then
-              export ZUUL_BRANCH=master
+          
+          set -xe
+
+          if [ -e /home/jenkins/xenapi-os-testing ]
+          then
+              rm -rf /home/jenkins/xenapi-os-testing
           fi
-          export PYTHONUNBUFFERED=true
-          export DEVSTACK_GATE_TEMPEST=1
-          export DEVSTACK_GATE_VIRT_DRIVER=libvirt
-          export DEVSTACK_GATE_LIBVIRT_TYPE=xen
-          export DEVSTACK_GATE_TIMEOUT=180
-          export DEVSTACK_GATE_TEMPEST_REGEX='(?!.*\[.*\bslow\b.*\]|.*test_volume_boot_pattern|.*test_shelve_volume_backed_instance)(^tempest\.(api|scenario|thirdparty))'
-          export RE_EXEC=true
-          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
-          ./safe-devstack-vm-gate-wrap.sh
+          
+          #export ZUUL_URL=https://review.openstack.org/p
+          #export ZUUL_PROJ_CHANGE=$(echo $ZUUL_CHANGES | tr '^' '\n' | grep $ZUUL_CHANGE)
+          #export ZUUL_REF=$(echo $ZUUL_PROJ_CHANGE | cut -d: -f3)
+          /usr/bin/git clone https://github.com/openstack/xenapi-os-testing.git /home/jenkins/xenapi-os-testing
+          if [ "$ZUUL_PROJECT" = "openstack/xenapi-os-testing" ]
+          then
+              cd /home/jenkins/xenapi-os-testing
+              #/usr/bin/git fetch https://review.openstack.org/openstack/xenapi-os-testing $ZUUL_REF
+              /usr/bin/git fetch $ZUUL_URL/openstack/xenapi-os-testing $ZUUL_REF
+              /usr/bin/git checkout FETCH_HEAD
+              cd -
+          fi
+          
+          sudo sed -i 's/DEVSTACK_GATE_BRANCH="master"/DEVSTACK_GATE_BRANCH="rebaseToResolveTempestRunError"/' /home/jenkins/xenapi-os-testing/run_tests.sh
+          sudo sed -i 's/^export ZUUL_URL=https:/#export ZUUL_URL=https:/g' /home/jenkins/xenapi-os-testing/run_tests.sh
+         
+          PYTHONUNBUFFERED=true DEVSTACK_GATE_TEMPEST=1 DEVSTACK_GATE_TEMPEST_FULL=1 \
+          DEVSTACK_GATE_VIRT_DRIVER=xenapi DEVSTACK_GATE_TIMEOUT=180 APPLIANCE_NAME=devstack \
+          ENABLED_SERVICES=g-api,g-reg,key,n-api,n-crt,n-obj,n-cpu,n-sch,horizon,mysql,rabbit,sysstat,dstat,pidstat,s-proxy,s-account,s-container,s-object,n-cond \
+          /home/jenkins/xenapi-os-testing/run_tests.sh 2>&1  | tee /home/jenkins/run_tests.log
+
+          if grep -q "Failed" ~/result.txt
+          then
+              exit 137
+          fi
+         
       - link-logs  # In macros.yaml from os-ext-testing
 
     publishers:
+      #- osci-swift-upload-logs:
       - osci-swift-upload-logs-with-console:
-          upload_source: 'logs'
+          upload_source: 'logs logs/run_tests.log'
+
+- job-template:
+    name: 'dsvm-tempest-neutron-network'
+    #name: 'check-citrix-xenserver-neutron'
+    node: '{node}'
+
+    wrappers:
+      - timeout:
+          timeout: 230  # Timeout in *minutes*
+          fail: true  # A job run that exceeds the timeout will cause a failure
+      - timestamps
+
+    builders:
+      - net-info
+      - shell: |
+          #!/bin/bash -xe
+          set +xe
+          sudo  sed -i '1i\192.168.33.2 localhost.localdomain' /etc/hosts
+          cd /opt/git/openstack-infra/devstack-gate
+          sudo /usr/bin/git remote update
+          sudo /usr/bin/git checkout origin/master
+          cd -
+          set -xe
+
+          if [ -e /home/jenkins/xenapi-os-testing ]
+          then
+              rm -rf /home/jenkins/xenapi-os-testing
+          fi
+          export ZUUL_URL=https://review.openstack.org/p
+          export ZUUL_PROJ_CHANGE=$(echo $ZUUL_CHANGES | tr '^' '\n' | grep $ZUUL_CHANGE)
+          export ZUUL_REF=$(echo $ZUUL_PROJ_CHANGE | cut -d: -f3)
+          /usr/bin/git clone https://github.com/openstack/xenapi-os-testing.git /home/jenkins/xenapi-os-testing
+          if [ "$ZUUL_PROJECT" = "openstack/xenapi-os-testing" ]
+          then
+              cd /home/jenkins/xenapi-os-testing
+              /usr/bin/git fetch https://review.openstack.org/openstack/xenapi-os-testing $ZUUL_REF
+              /usr/bin/git checkout FETCH_HEAD
+              cd -
+          fi
+ 
+          RUN_SHELL=/home/jenkins/xenapi-os-testing/run_tests.sh
+
+          sudo sed -i 's/DEVSTACK_GATE_BRANCH="master"/DEVSTACK_GATE_BRANCH="rebaseToResolveTempestRunError"/' /home/jenkins/xenapi-os-testing/run_tests.sh
+          
+          PYTHONUNBUFFERED=true DEVSTACK_GATE_TEMPEST=1 DEVSTACK_GATE_TEMPEST_FULL=1 \
+          DEVSTACK_GATE_VIRT_DRIVER=xenapi DEVSTACK_GATE_TIMEOUT=180 APPLIANCE_NAME=devstack \
+          DEVSTACK_GATE_NEUTRON=1 \
+          ENABLED_SERVICES=q-domua,g-api,g-reg,key,n-api,n-crt,n-obj,n-cpu,n-sch,horizon,mysql,rabbit,sysstat,dstat,pidstat,s-proxy,s-account,s-container,s-object,n-cond \
+          /home/jenkins/xenapi-os-testing/run_tests.sh 2>&1  | tee /home/jenkins/run_tests.log
+
+          if grep -q "Failed" ~/result.txt
+          then
+              exit 137
+          fi
+         
+      - link-logs  # In macros.yaml from os-ext-testing
+
+    publishers:
+      #- osci-swift-upload-logs:
+      - osci-swift-upload-logs-with-console:
+          upload_source: 'logs logs/run_tests.log'
+
+- job-template:
+    name: 'check-fuel-xenserver-plugin'
+    node: '{node}'
+
+    wrappers:
+      - timeout:
+          timeout: 185  # Timeout in *minutes*
+          fail: true  # A job run that exceeds the timeout will cause a failure
+      - timestamps
+
+    builders:
+      #- net-info
+      - shell: |
+         #!/bin/bash -xe
+          env
+          
+          #If disable ceilometer by force
+          export FORCE_DISABLE_CEILOMETER=""
+          export ZUUL_CHANGES=${ZUUL_CHANGES:-""}
+          
+          #ZUUL_REFSPEC=refs/changes/63/378663/1
+          
+          echo "Testing fuel xenserver plugin"
+          export FUEL_TEST_LOG_DIR=$WORKSPACE/logs
+          LOG=$WORKSPACE/test.log
+          rm -rf $WORKSPACE
+          mkdir -p $WORKSPACE
+          mkdir -p $FUEL_TEST_LOG_DIR
+          cd $WORKSPACE
+          git clone https://github.com/citrix-openstack/qa -b CorrectBranchAndDepends
+          cd qa/fuel_test
+          cp localrc.default localrc
+          #export XS_HOST="venamis.xenrt.citrite.net"
+          export XS_HOST=$(hostname | cut -d'-' -f2).xenrt.citrite.net
+          export FM_MNT="10.71.77.230:/data/exports"
+          export FM_PWD="r00tme"
+          export ZUUL_URL="http://10.71.212.50/p"
+          #export FUEL_PLUGIN_REFSPEC=${ZUUL_REFSPEC:-""}
+          export IXE_NFS="10.62.16.21:/openstack"
+          export IXE_ISO="ipxe_20160809.iso"
+          export FUEL_TEST_SUCCESS=$WORKSPACE/fuel_test_sucess
+          rm -f $FUEL_TEST_SUCCESS
+          
+          ./fuel_test.sh 2>&1| tee -a $LOG
+          
+          if [ ! -f $FUEL_TEST_SUCCESS ]; then
+              exit 137
+          fi
+            
+    publishers:
+      - osci-swift-upload-logs-with-console-plugin:
+          upload_source: 'test.log logs'
+
+- job-template:
+    name: 'check-fuel-xenserver-6.5-plugin'
+    node: '{node}'
+
+    wrappers:
+      - timeout:
+          timeout: 185  # Timeout in *minutes*
+          fail: true  # A job run that exceeds the timeout will cause a failure
+      - timestamps
+
+    builders:
+      #- net-info
+      - shell: |
+          #!/bin/bash -xe
+          env
+          
+          # If disable ceilometer by force
+          export FORCE_DISABLE_CEILOMETER=""
+          export ZUUL_CHANGES=${ZUUL_CHANGES:-""}
+          
+          echo "Testing fuel xenserver plugin"
+          export FUEL_TEST_LOG_DIR=$WORKSPACE/logs
+          LOG=$WORKSPACE/test.log
+          rm -rf $WORKSPACE
+          mkdir -p $WORKSPACE
+          mkdir -p $FUEL_TEST_LOG_DIR
+          cd $WORKSPACE
+          git clone https://github.com/citrix-openstack/qa -b CorrectBranchAndDepends
+          cd qa/fuel_test
+          cp localrc.default localrc
+          #export XS_HOST="venamis.xenrt.citrite.net"
+          export XS_HOST=$(hostname | cut -d'-' -f2).xenrt.citrite.net
+          export FM_MNT="10.71.77.230:/data/exports"
+          export FM_PWD="r00tme"
+          export ZUUL_URL="http://10.71.212.50/p"
+          #export FUEL_PLUGIN_REFSPEC=${ZUUL_REFSPEC:-""}
+          export IXE_NFS="10.62.16.21:/openstack"
+          export IXE_ISO="ipxe_20160809.iso"
+          export FUEL_TEST_SUCCESS=$WORKSPACE/fuel_test_sucess
+          rm -f $FUEL_TEST_SUCCESS
+          
+          ./fuel_test.sh 2>&1| tee -a $LOG
+          
+          if [ ! -f $FUEL_TEST_SUCCESS ]; then
+              exit 137
+          fi
+
+    publishers:
+      - osci-swift-upload-logs-with-console-plugin:
+          upload_source: 'test.log logs'
